### ISSUE TITLE
slf4j-log4j not work

### ISSUE THREAD

**Issue by aaryadewa** [reegnz/struts-cdi#1]
The logger outputs nothing after installed the struts-cdi.

I put **log.debug** in an ActionBean. But it display nothing. The EJB bean has been injected with no problem. I can make a call to its method with the expected result. The only think is that the logger outputs nothing.

I'm using JBoss EAP 6.4 and the application is deployed as a standalone app. Set the log4j level to DEBUG. Using Struts 1.3.

**Comment by reegnz** [comment]
Closing issue as logger configuration is part of struts, not this code.
